export const LOAD_RESULT = 'LOAD_RESULT';
export const LOAD_ERROR = 'LOAD_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const UPDATE_KEYWORD = 'UPDATE_KEYWORD';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_SELECTED_FILTER = 'REMOVE_SELECTED_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
export const UPDATE_PAGE_NUM = 'UPDATE_PAGE_NUM';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_FIELDS = 'UPDATE_FIELDS';
export const UPDATE_SHOW_ALL = 'UPDATE_SHOW_ALL';
export const UPDATE_HAS_FILTER = 'UPDATE_HAS_FILTER';
export const RESET_PAGE_NUM = 'RESET_PAGE_NUM';

export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';

export const TOGGLE_WHICH = 'TOGGLE_WHICH';
